### ISSUE TITLE
 libgamma_error.LibgammaError: LIBGAMMA_GAMMA_RAMP_WRITE_FAILED

### ISSUE THREAD

**Issue by max-te** [maandree/blueshift#21]
Since updating my system yesterday (including updating xorg-* to 1.20), blueshift does not start for me, but crashes with this output:
```
$ blueshift -c /usr/share/doc/blueshift/examples/bedtime
Traceback (most recent call last):
  File "/usr/bin/blueshift/__main__.py", line 467, in continuous_run
  File "/usr/bin/blueshift/__main__.py", line 360, in p
  File "/usr/share/doc/blueshift/examples/bedtime", line 287, in periodically
    apply_curves()
  File "/usr/bin/blueshift/monitor.py", line 147, in randr
  File "/usr/bin/blueshift/monitor.py", line 80, in set_gamma
  File "/usr/lib/python3.6/libgamma_method.py", line 1116, in set_gamma
    raise create_error(r)
libgamma_error.LibgammaError: LIBGAMMA_GAMMA_RAMP_WRITE_FAILED

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/bin/blueshift/__main__.py", line 742, in <module>
  File "/usr/bin/blueshift/__main__.py", line 546, in continuous_run
  File "/usr/share/doc/blueshift/examples/bedtime", line 310, in reset
    apply_curves()
  File "/usr/bin/blueshift/monitor.py", line 147, in randr
  File "/usr/bin/blueshift/monitor.py", line 80, in set_gamma
  File "/usr/lib/python3.6/libgamma_method.py", line 1116, in set_gamma
    raise create_error(r)
libgamma_error.LibgammaError: LIBGAMMA_GAMMA_RAMP_WRITE_FAILED
Exception ignored in: <bound method Site.__del__ of <libgamma_method.Site object at 0x7f6e9ad14fd0>>
Traceback (most recent call last):
  File "/usr/lib/python3.6/libgamma_method.py", line 947, in __del__
ImportError: sys.meta_path is None, Python is likely shutting down
Exception ignored in: <bound method Partition.__del__ of <libgamma_method.Partition object at 0x7f6e9ac7d3c8>>
Traceback (most recent call last):
  File "/usr/lib/python3.6/libgamma_method.py", line 1000, in __del__
ImportError: sys.meta_path is None, Python is likely shutting down
Exception ignored in: <bound method CRTC.__del__ of <libgamma_method.CRTC object at 0x7f6e9ac7d470>>
Traceback (most recent call last):
  File "/usr/lib/python3.6/libgamma_method.py", line 1046, in __del__
ImportError: sys.meta_path is None, Python is likely shutting down
```

**Comment by maandree** [comment]
I'm still on 1.19.6. Does redshift work for you? What happens if you roll back to an older version of X.org?

**Comment by max-te** [comment]
It does work if i roll back just xorg-server to 1.19.6+13+gd0d1a694f-2, the version I had before (this is on Arch Linux).
Redshift using randr still works for me on 1.20.

**Comment by maandree** [comment]
Thank you! I will look into this next time a reboot the computer (which is hopefully today or tomorrow).

**Comment by maandree** [comment]
I am unable to get 1.20.0 running on my computer, but I will see if I can get it running om another computer.

**Comment by eriktux** [comment]
Same here.  I did a system upgrade today (Arch Linux) and since then, my redshift started to behave in a very weird fashion.

That's why I found blueshift!   I thought it was time for me to "shift" to a new software.  But I'm getting the same error msg as max-te here.

xorg-server 1.20.0-2
RandR 1.5

I'm willing to help!   What should I downgrade first, for testing?

**Comment by maandree** [comment]
I think you should report this to the X.org developers. You can also finding the problem in https://github.com/maandree/libgamma. I'm still unable to start X.org 1.20, but I will get installation USB and debug from there.

**Comment by podiki** [comment]
Same problem here (also on Arch, same versions as others have reported).

What exactly would be reported to X.org developers? This seems be an issue in libgamma, or are you saying that is exposing a bug in X.org?

**Comment by maandree** [comment]
I'm not sure what the exact problem is yet, but since it works in X.org 1.19 either something in X.org 1.20 is broken, the API has changed, or libgamma misused to the API and X.org 1.20 has become more strict. I would suggest just sending link to this bug report.

**Comment by maandree** [comment]
I'm unable to reproduce this in 1.20.0, pkgrel 9 in Arch. Is this still a problem?

**Comment by maandree** [comment]
Does `blueshift -pt 4000` work?

**Comment by max-te** [comment]
Ah, sorry I was busy with another issue. Anyway, this issue is driver dependent.
It appears on my desktop with the Nvidia binary driver and on my laptop with Intel Integrated Graphics and the modesetting driver, but if I use the `xf86-video-intel` driver on my laptop it's fine.

**Comment by podiki** [comment]
> Does `blueshift -pt 4000` work?

Nope, same problem. (Sorry missed the question before.)

**Comment by podiki** [comment]
I'm using `xf86-video-intel` on my laptop with Intel graphics (there is Nvidia also, but I use bumblee just to turn it on for select programs) and am having the problem.

**Comment by podiki** [comment]
I've just checked and everything seems to be working now (latest Xorg, graphics drivers, etc.). I wish I could be more specific so we know what happened, but forgot to try until now. Glad it is working again!

**Comment by podiki** [comment]
Update: blueshift currently works on latest Xorg and Intel graphics, but not on Nvidia. Same error as before.

**Comment by podiki** [comment]
Me again. Fix noted at top of Readme works for me on latest Xorg and Nvidia graphics (not needed on Intel).
